CREATE TABLE ELECTRONICS(PID INT PRIMARY KEY,CAT_ID INT FOREIGN KEY REFERENCES PROD_CAT(CAT_ID),PNAME VARCHAR(10),PRICE INT,QUANTITY INT,WARRANTY INT,DISCOUNT INT);
INSERT INTO ELECTRONICS VALUES(2,4,'SAMSUNG',40000,20,15,1);
INSERT INTO ELECTRONICS VALUES(3,4,'XOLO',42000,0,15,1);
INSERT INTO ELECTRONICS VALUES(4,2,'WASHING-MACHINE',10000,10,15,1);

DROP TABLE ELECSALES
CREATE TABLE PROD_CAT(DEPTID INT FOREIGN KEY REFERENCES DEPT(DEPTID),CAT_ID INT PRIMARY KEY,CAT_NAME VARCHAR(20))
CREATE TABLE DEPT(DEPTID INT PRIMARY KEY,DEPTNAME VARCHAR(20),DEPTST_NO VARCHAR(20))

CREATE TABLE ELECSALES(PID INT ,CUST_NAME VARCHAR(20),UID INT FOREIGN KEY REFERENCES LOGIN(UID),DATE_SELL DATE,QTY INT, PRICE INT,SALES_ID INT PRIMARY KEY);
INSERT INTO ELECSALES VALUES(3,'NISHA',508,'2017-07-16',2,42000);
INSERT INTO ELECSALES VALUES(2,'NIKITA',509,'2017-08-16',2,40000);
INSERT INTO ELECSALES VALUES(1,'RAJRR',510,'2017-07-16',4,10000);

CREATE TABLE LOGIN(UID INT IDENTITY(500,1) PRIMARY KEY,PASSWORD VARCHAR(10))
ALTER TABLE LOGIN ADD CUST_NAME VARCHAR(20);

CREATE TABLE CANCEL_ORDER_ELEC(PID INT,CUST_NAME VARCHAR(20),UID INT,DATE_CANCEL DATE,QTY INT, PRICE INT,TOT_PRICE INT,CANCELLED_ID INT PRIMARY KEY);

CREATE TABLE EMPLOYEE(EMPID INT PRIMARY KEY,FNAME VARCHAR(20),MNAME VARCHAR(20),LNAME VARCHAR(20),EMP_SAL INT,DEPTID INT,ACCNO INT,BANK_NAME VARCHAR(20),ADDRESS VARCHAR(20))

CREATE TABLE FACTSALES(PID INT FOREIGN KEY REFERENCES ELECTRONICS,EMPID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPID),SALES_ID INT FOREIGN KEY REFERENCES ELECSALES(SALES_ID),CANCELLED_ID INT FOREIGN KEY REFERENCES CANCEL_ORDER_ELEC(CANCELLED_ID),TOTAL_SALES INT,TOTAL_QUANTITY INT,TOTAL_PROFIT INT,TOTAL_LOSS INT,TOTAL_CANCELLED_ORDERS INT ,EMPLOYEE_RECORD INT);

DROP TABLE FACTSALES
CREATE TABLE COSMETIC(PID INT PRIMARY KEY,CAT_ID INT,PNAME VARCHAR(20),PRICE INT,QUANTITY INT,DISCOUNT INT)
CREATE TABLE COSSALES(PID INT,CUSTNAME VARCHAR(20),UID INT,QTY INT,PRICE INT,TOT_PRICE INT,SALES_ID INT PRIMARY KEY)


CREATE TABLE FACTSALESCOSMETIC(PID INT FOREIGN KEY REFERENCES COSMETIC,EMPID INT FOREIGN KEY REFERENCES EMPLOYEE(EMPID),SALES_ID INT FOREIGN KEY REFERENCES COSSALES(SALES_ID),TOTAL_SALES INT,TOTAL_QUANTITY INT,TOTAL_PROFIT INT ,EMPLOYEE_RECORD INT);